# Generated by Django 6.0.2 on 2026-03-15 05:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=230)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'FREE'), ('pro', 'PRO'), ('enterprice', 'ENTERPRICE')], default='free', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
                'indexes': [models.Index(fields=['slug'], name='companies_slug_e0676c_idx'), models.Index(fields=['plan_type'], name='companies_plan_ty_5d52f5_idx')],
            },
        ),
    ]
